### ISSUE TITLE
Error 404.

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [rushkii/abyss-card#9]
![image](https://user-images.githubusercontent.com/98014624/233150944-42b7daa1-79f7-4874-9613-7dc9330931be.png)
![image](https://user-images.githubusercontent.com/98014624/233151024-06ae2956-79e3-4a3b-8fd1-deb518608785.png)
When I entered my UID and pressed enter, an error came out. It is noteworthy that everything works on enka.network, although abyss-card works on its api

**Comment by rushkii** [comment]
> ![image](https://user-images.githubusercontent.com/98014624/233150944-42b7daa1-79f7-4874-9613-7dc9330931be.png) ![image](https://user-images.githubusercontent.com/98014624/233151024-06ae2956-79e3-4a3b-8fd1-deb518608785.png) When I entered my UID and pressed enter, an error came out. It is noteworthy that everything works on enka.network, although abyss-card works on its api

It was clearly written in README that this project is still unfinished.
